package org.bepass.oblivion.dns

object DnsBuiltInProviders {
  private const val VERIFIED_AT = "2026-06-29"
  private const val CONTROL_D_SOURCE = "https://docs.controld.com/docs/free-dns"

  val additional: List<DnsProvider> =
    listOf(
      provider(
        id = "cloudflare-security",
        label = "Cloudflare Security",
        country = "US",
        ips = listOf("1.1.1.2", "1.0.0.2"),
        dohUrl = "https://security.cloudflare-dns.com/dns-query",
        dotHost = "security.cloudflare-dns.com",
        tags = listOf("security", "malware"),
        sourceUrl = "https://developers.cloudflare.com/1.1.1.1/setup/",
      ),
      provider(
        id = "cloudflare-family",
        label = "Cloudflare Family",
        country = "US",
        ips = listOf("1.1.1.3", "1.0.0.3"),
        dohUrl = "https://family.cloudflare-dns.com/dns-query",
        dotHost = "family.cloudflare-dns.com",
        tags = listOf("family", "security"),
        sourceUrl = "https://developers.cloudflare.com/1.1.1.1/setup/",
      ),
      provider(
        id = "adguard-default",
        label = "AdGuard Default",
        country = "CY",
        ips = listOf("94.140.14.14", "94.140.15.15"),
        dohUrl = "https://dns.adguard-dns.com/dns-query",
        dotHost = "dns.adguard-dns.com",
        tags = listOf("ads", "tracking", "security"),
        sourceUrl = "https://adguard-dns.io/en/public-dns.html",
      ),
      provider(
        id = "adguard-family",
        label = "AdGuard Family",
        country = "CY",
        ips = listOf("94.140.14.15", "94.140.15.16"),
        dohUrl = "https://family.adguard-dns.com/dns-query",
        dotHost = "family.adguard-dns.com",
        tags = listOf("family", "ads", "security"),
        sourceUrl = "https://adguard-dns.io/en/public-dns.html",
      ),
      provider(
        id = "quad9-unsecured",
        label = "Quad9 Unsecured",
        country = "CH",
        ips = listOf("9.9.9.10", "149.112.112.10"),
        dohUrl = "https://dns10.quad9.net/dns-query",
        dotHost = "dns10.quad9.net",
        tags = listOf("privacy", "unfiltered"),
        sourceUrl = "https://docs.quad9.net/services/",
      ),
      provider(
        id = "quad9-secure-ecs",
        label = "Quad9 Secure + ECS",
        country = "CH",
        ips = listOf("9.9.9.11", "149.112.112.11"),
        dohUrl = "https://dns11.quad9.net/dns-query",
        dotHost = "dns11.quad9.net",
        tags = listOf("security", "ecs"),
        sourceUrl = "https://docs.quad9.net/services/",
      ),
      provider(
        id = "quad9-unsecured-ecs",
        label = "Quad9 Unsecured + ECS",
        country = "CH",
        ips = listOf("9.9.9.12", "149.112.112.12"),
        dohUrl = "https://dns12.quad9.net/dns-query",
        dotHost = "dns12.quad9.net",
        tags = listOf("unfiltered", "ecs"),
        sourceUrl = "https://docs.quad9.net/services/",
      ),
      provider(
        id = "cleanbrowsing-family",
        label = "CleanBrowsing Family",
        country = "US",
        ips = listOf("185.228.168.168", "185.228.169.168"),
        dohUrl = "https://doh.cleanbrowsing.org/doh/family-filter/",
        dotHost = "family-filter-dns.cleanbrowsing.org",
        tags = listOf("family", "security"),
        sourceUrl = "https://cleanbrowsing.org/support/troubleshooting/firewall-dns-requirements",
      ),
      provider(
        id = "cleanbrowsing-adult",
        label = "CleanBrowsing Adult",
        country = "US",
        ips = listOf("185.228.168.10", "185.228.169.11"),
        dohUrl = "https://doh.cleanbrowsing.org/doh/adult-filter/",
        dotHost = "adult-filter-dns.cleanbrowsing.org",
        tags = listOf("adult-filter", "security"),
        sourceUrl = "https://cleanbrowsing.org/support/troubleshooting/firewall-dns-requirements",
      ),
      controlD("controld-malware", "Control D Malware", "p1", 1, "malware"),
      controlD("controld-ads", "Control D Ads & Tracking", "p2", 2, "ads", "tracking"),
      controlD("controld-social", "Control D Social", "p3", 3, "social"),
      controlD("controld-family", "Control D Family", "family", 4, "family"),
      controlD("controld-uncensored", "Control D Uncensored", "uncensored", 5, "uncensored"),
      controlD("controld-oisd", "Control D OISD Full", "x-oisd", 32, "oisd", "ads"),
      controlD(
        "controld-oisd-basic",
        "Control D OISD Basic",
        "x-oisd-basic",
        33,
        "oisd",
        "ads",
      ),
      controlD(
        "controld-stevenblack",
        "Control D StevenBlack",
        "x-stevenblack",
        35,
        "ads",
      ),
      controlD("controld-1hosts-lite", "Control D 1Hosts Lite", "x-1hosts-lite", 38, "ads"),
      controlD("controld-1hosts-pro", "Control D 1Hosts Pro", "x-1hosts-pro", 39, "ads"),
      controlD("controld-1hosts-xtra", "Control D 1Hosts Xtra", "x-1hosts-xtra", 48, "ads"),
      controlD(
        "controld-hagezi-light",
        "Control D HaGeZi Light",
        "x-hagezi-light",
        37,
        "ads",
      ),
      controlD(
        "controld-hagezi-normal",
        "Control D HaGeZi Normal",
        "x-hagezi-normal",
        40,
        "ads",
      ),
      controlD("controld-hagezi-pro", "Control D HaGeZi Pro", "x-hagezi-pro", 41, "ads"),
      controlD(
        "controld-hagezi-proplus",
        "Control D HaGeZi Pro Plus",
        "x-hagezi-proplus",
        42,
        "ads",
      ),
      controlD(
        "controld-hagezi-ultimate",
        "Control D HaGeZi Ultimate",
        "x-hagezi-ultimate",
        45,
        "ads",
      ),
      controlD("controld-hagezi-tif", "Control D HaGeZi TIF", "x-hagezi-tif", 46, "threats"),
      controlD(
        "controld-goodbyeads",
        "Control D GoodbyeAds",
        "x-goodbyeads",
        43,
        "ads",
      ),
      controlD("controld-adguard", "Control D AdGuard Filter", "x-adguard", 44, "ads"),
      controlD("controld-hblock", "Control D hBlock", "x-hblock", 47, "ads"),
    )

  private fun controlD(
    id: String,
    label: String,
    endpoint: String,
    addressSuffix: Int,
    vararg tags: String,
  ): DnsProvider =
    provider(
      id = id,
      label = label,
      country = "CA",
      ips = listOf("76.76.2.$addressSuffix", "76.76.10.$addressSuffix"),
      dohUrl = "https://freedns.controld.com/$endpoint",
      dotHost = "$endpoint.freedns.controld.com",
      tags = tags.toList() + listOf("controld", "public"),
      sourceUrl = CONTROL_D_SOURCE,
    )

  private fun provider(
    id: String,
    label: String,
    country: String,
    ips: List<String>,
    dohUrl: String,
    dotHost: String,
    tags: List<String>,
    sourceUrl: String,
  ): DnsProvider =
    DnsProvider(
      providerId = id,
      label = label,
      country = country,
      regionGroup = "International",
      transports =
        setOf(
          DnsTransport.PLAIN,
          DnsTransport.UDP,
          DnsTransport.TCP,
          DnsTransport.DOH,
          DnsTransport.DOT,
        ),
      plainIps = ips,
      bootstrapIps = ips,
      dohUrl = dohUrl,
      dotHost = dotHost,
      ports =
        mapOf(
          DnsTransport.PLAIN to DNS_PORT,
          DnsTransport.UDP to DNS_PORT,
          DnsTransport.TCP to DNS_PORT,
          DnsTransport.DOH to DNS_HTTPS_PORT,
          DnsTransport.DOT to DNS_TLS_PORT,
        ),
      tags = tags,
      sourceUrl = sourceUrl,
      verifiedAt = VERIFIED_AT,
      unverified = false,
    )
}
